# mod
mod_id=tradestages
mod_name=TradeStages Legacy
mod_version=1.0.0
mod_author=["Nischhelm", "Quarris"]
mod_description=Backport of TradeStages to 1.12.2, allows to gate villager trades behind game stages
mixin_loader_class=tradestages.TradeStagesPlugin

# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false
org.gradle.caching=true

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12
fancy_gradle_version=1.1.+
mod_publish_gradle_version=2.0.0

# mixin
mixin_gradle_version=0.7.+
mixin_version=0.8.7
mixin_extras_version=0.5.4

publish_to_github=false
curseforge_project_id=1638884
modrinth_project_id=wxepSEb5